# Generated by Django 5.2.1 on 2025-05-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_poll_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('user_options', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_polls', to='users.userprofilemodel')),
            ],
        ),
    ]
