# Generated by Django 5.2.1 on 2025-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('completed_polls', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
