# Generated by Django 5.2.1 on 2025-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_pollmodel_user_profile'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='passed_polls',
            field=models.ManyToManyField(blank=True, related_name='users_passed', to='polls.pollmodel'),
        ),
    ]
